osx_image: xcode10.2
language: objective-c
xcode_workspace: CompleteRedux.xcworkspace
xcode_scheme: CompleteRedux
xcode_sdk: iphonesimulator12.1
before_install:
  - gem install cocoapods
  - gem install slather
  - gem install xcpretty
  - pod install

script:
  - set -o pipefail && xcodebuild clean test -sdk iphonesimulator -workspace CompleteRedux.xcworkspace -scheme CompleteRedux -destination 'platform=iOS Simulator,name=iPhone 8 Plus' | xcpretty
  - pod lib lint --quick

after_success:
  - slather coverage --workspace CompleteRedux.xcworkspace
  - bash <(curl -s https://codecov.io/bash) -f xml_report/cobertura.xml -X coveragepy -X gcov -X xcode
