osx_image: xcode10.1
language: objective-c
xcode_workspace: ReactiveRedux.xcworkspace
xcode_scheme: ReactiveRedux
xcode_sdk: iphonesimulator11.2
before_install:
  - gem install cocoapods --pre
  - gem install slather xcpretty
  - pod repo update

script:
  - set -o pipefail && xcodebuild clean test -sdk iphonesimulator -workspace ReactiveRedux.xcworkspace -scheme ReactiveRedux -destination 'platform=iOS Simulator,name=iPhone 7' | xcpretty
  - pod lib lint --quick

after_success: slather
