osx_image: xcode10.1
language: objective-c
xcode_workspace: SwiftRedux.xcworkspace
xcode_scheme: SwiftRedux
xcode_sdk: iphonesimulator11.2
before_install:
  - gem install cocoapods --pre
  - gem install slather --pre
  - gem install xcpretty
  - pod repo update

script:
  - set -o pipefail && xcodebuild clean test -sdk iphonesimulator -workspace SwiftRedux.xcworkspace -scheme SwiftRedux -destination 'platform=iOS Simulator,name=iPhone 7' | xcpretty
  - pod lib lint --quick

after_success:
  - slather coverage --workspace SwiftRedux.xcworkspace
  - bash <(curl -s https://codecov.io/bash) -f xml_report/cobertura.xml -X coveragepy -X gcov -X xcode
